"""PKGBUILD generation and makepkg invocation."""

import os
import shlex
import subprocess
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from . import PROJECT_URL
from .i18n import _
from .layout import merge_rules
from .version import PacmanVersion

PACKAGE_OPTIONS = ("!strip", "!debug", "!zipman", "!purge", "!lto", "!libtool", "!staticlibs", "emptydirs")


@dataclass
class PackageSpec:
    pkgname: str
    version: PacmanVersion
    pkgdesc: str
    arch: str
    url: str = ""
    license: str = "LicenseRef-custom"
    depends: list[str] = field(default_factory=list)
    optdepends: dict[str, str] = field(default_factory=dict)
    provides: list[str] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)
    backup: list[str] = field(default_factory=list)
    owners: dict[str, tuple[str, str]] = field(default_factory=dict)
    install: str | None = None


def _array(name: str, values) -> str:
    values = list(values)
    if not values:
        return ""
    if len(values) <= 3:
        return f"{name}=({' '.join(shlex.quote(v) for v in values)})\n"
    body = "".join(f"    {shlex.quote(v)}\n" for v in values)
    return f"{name}=(\n{body})\n"


def _header(spec: PackageSpec) -> str:
    v = spec.version
    text = f"# Generated by debtap-mod ({PROJECT_URL})\n\n"
    text += f"pkgname={shlex.quote(spec.pkgname)}\n"
    text += f"pkgver={shlex.quote(v.pkgver)}\n"
    text += f"pkgrel={shlex.quote(v.pkgrel)}\n"
    if v.epoch:
        text += f"epoch={v.epoch}\n"
    text += f"pkgdesc={shlex.quote(spec.pkgdesc)}\n"
    text += f"arch=({shlex.quote(spec.arch)})\n"
    if spec.url:
        text += f"url={shlex.quote(spec.url)}\n"
    text += f"license=({shlex.quote(spec.license)})\n"
    text += _array("depends", spec.depends)
    text += _array("optdepends", [f"{k}: {v}" for k, v in spec.optdepends.items()])
    text += _array("provides", spec.provides)
    text += _array("conflicts", spec.conflicts)
    text += _array("backup", spec.backup)
    text += _array("options", PACKAGE_OPTIONS)
    if spec.install:
        text += f"install={shlex.quote(spec.pkgname + '.install')}\n"
    return text


def _chown_lines(spec: PackageSpec) -> str:
    lines = ""
    for path, (user, group) in sorted(spec.owners.items()):
        lines += f"    chown -h {shlex.quote(user + ':' + group)} \"$pkgdir\"/{shlex.quote(path)} 2>/dev/null || true\n"
    return lines


def write_build_dir(spec: PackageSpec, workdir: Path) -> None:
    """PKGBUILD used for the local build: it hard-links the prepared tree."""
    text = _header(spec)
    text += (
        "\npackage() {\n"
        '    cp -al "$startdir/root/." "$pkgdir/" 2>/dev/null || cp -a "$startdir/root/." "$pkgdir/"\n'
        + _chown_lines(spec)
        + "}\n"
    )
    (workdir / "PKGBUILD").write_text(text)
    if spec.install:
        (workdir / f"{spec.pkgname}.install").write_text(spec.install)


def write_portable(spec: PackageSpec, deb_path: Path, dest: Path, removed: list[str]) -> Path:
    """AUR-style PKGBUILD that rebuilds the package from the .deb file."""
    dest.mkdir(parents=True, exist_ok=True)
    debfile = deb_path.name
    text = _header(spec)
    text += f"source=({shlex.quote(debfile)})\n"
    text += "sha256sums=('SKIP')\n"
    text += "noextract=(" + shlex.quote(debfile) + ")\n"
    text += "\npackage() {\n"
    text += f'    bsdtar -xOf "$srcdir/{debfile}" "data.tar*" | bsdtar -xpf - -C "$pkgdir"\n'
    text += '    cd "$pkgdir"\n'
    for src, dst in merge_rules(spec.arch):
        text += (
            f"    if [[ -d {src} && ! -L {src} ]]; then mkdir -p {dst}; "
            f"cp -a --remove-destination {src}/. {dst}/; rm -rf {src}; fi\n"
        )
    for path in removed:
        text += f"    rm -rf {shlex.quote(path)}\n"
    text += _chown_lines(spec)
    text += "}\n"
    (dest / "PKGBUILD").write_text(text)
    if spec.install:
        (dest / f"{spec.pkgname}.install").write_text(spec.install)
    link = dest / debfile
    if not link.exists():
        os.symlink(deb_path.resolve(), link)
    return dest / "PKGBUILD"


MAKEPKG_CONF = """\
[[ -r /etc/makepkg.conf ]] && source /etc/makepkg.conf
for _conf in /etc/makepkg.conf.d/*.conf; do [[ -r $_conf ]] && source "$_conf"; done
unset _conf
PKGEXT='.pkg.tar.zst'
COMPRESSZST=(zstd -c -T0 -3 -)
"""


class BuildError(Exception):
    def __init__(self, message: str, log: str = ""):
        super().__init__(message)
        self.log = log


def run_makepkg(
    workdir: Path,
    log: Callable[[str], None] | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> Path:
    if os.geteuid() == 0:
        raise BuildError(_("makepkg cannot run as root; run debtap-mod as a regular user."))
    outdir = workdir / "out"
    outdir.mkdir(exist_ok=True)
    conf = workdir / "makepkg.conf"
    conf.write_text(MAKEPKG_CONF)
    env = {
        **os.environ,
        "LC_ALL": "C",
        "BUILDDIR": str(workdir / "build"),
        "PKGDEST": str(outdir),
        "SRCDEST": str(workdir / "srcdest"),
        "LOGDEST": str(workdir),
        "PKGEXT": ".pkg.tar.zst",
        "PACKAGER": f"debtap-mod <{PROJECT_URL}>",
    }
    cmd = ["makepkg", "--config", str(conf), "-f", "-d", "--noconfirm", "--noprogressbar", "--nocolor"]
    proc = subprocess.Popen(
        cmd, cwd=workdir, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1
    )
    output = []
    for line in proc.stdout:
        output.append(line)
        if log:
            log(line.rstrip("\n"))
        if cancelled and cancelled():
            proc.terminate()
    proc.wait()
    if proc.returncode != 0:
        raise BuildError(_("makepkg failed with exit code {code}").format(code=proc.returncode), "".join(output))
    packages = sorted(outdir.glob("*.pkg.tar*"))
    if not packages:
        raise BuildError(_("makepkg finished but produced no package"), "".join(output))
    return packages[0]
